version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker      
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: | 
            heroku container:login
            heroku stack:set container -a az2366-su-devops
            heroku container:push web -a az2366-su-devops
            heroku container:release web -a az2366-su-devops
  scan:
    docker:
      - image:  cimg/node:16.10
    environment:
      IMAGE_NAME: az2366/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run:  docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name:  $IMAGE_NAME

  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/education-space:$CIRCLE_SHA1 .
      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/education-space:$CIRCLE_SHA1

workflows:
  simple_workflow:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      # - publish:
      #     requires:
      #       - test
      # - deploy:
      #     requires:
      #       - publish
      - scan:
          requires:
            - build
      - test:
          requires:
            - scan