version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.1  

jobs: 
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install
  
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests"
          npm run test

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout  
      - setup_remote_docker:
          docker_layer_caching: true  
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/education-space:$CIRCLE_SHA1 .  # Build image
      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin  # Login to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/education-space:$CIRCLE_SHA1  # Push image to Docker Hub

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build  
      - build-and-push:
          requires:
            - test  
          filters:
            branches:
              only:
                - main  
